//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMark
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public string ExamName { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public string Session { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
