//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collage_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.ExamMarks = new HashSet<ExamMark>();
        }
    
        public int StudentId { get; set; }
        [Display(Name ="S.Name")]
        public string StudentName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Session { get; set; }
        [Display(Name ="Dept")]
        public Nullable<int> DepartmentId { get; set; }
        [Display(Name ="Sem:")]
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMark> ExamMarks { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual User User { get; set; }
    }
}
